"""Added status to uploadsession

Revision ID: e8265ffd46e8
Revises: b73bbd7b7c97
Create Date: 2022-07-23 16:05:31.362761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8265ffd46e8'
down_revision = 'b73bbd7b7c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_session', sa.Column('has_uploaded', sa.Boolean(), nullable=False))
    op.alter_column('upload_session', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_session', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('upload_session', 'has_uploaded')
    # ### end Alembic commands ###
